language: python # => 1

python: # => 3
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install django
  - pip install coverage
  - pip install django-nose
  - pip install selenium
  - pip install webdriver-manager

script:
  - python manage.py runserver
  - python manage.py test --cover-package=web
